### ISSUE TITLE
Notification for Navigate > Back action shows up when using mouse button 4.

### ISSUE THREAD

**Issue by deadmoto** [halirutan/IntelliJ-Key-Promoter-X#10]
The issue occurs in Android Studio on Mac OS X.
Both 2.3.3 and 3.0 Beta 7 versions are affected.
Keymap settings have Mouse button 4 assigned for the Navigate > Back action, but when the button 4 is pressed, the notification shows up suggesting to use mouse button 4.

**Comment by halirutan** [comment]
Yes, this is correct. On Linux, it first of all says which keys you can use

![img](http://i.imgur.com/10D2HoA.png)

I don't create the suggestions by myself. The information about the shortcut come directly from the IDEA action itself. There is nothing much I can do about this. What the KeyPromoter sees is:

1. You clicked the mouse
2. The click invoked some action that I can inspect
3. The action has a short-cut description, so the KeyPromoter can show it to you

Inspecting the string descriptions itself is something I don't want to do. I see it as a tremendous task to get this right when those things like button click 4 are rare cases where users don't press an actual button. Sorry.
