### ISSUE TITLE
Don't count using a mouse shortcut as having missed a keyboard shortcut

### ISSUE THREAD

**Issue by bcye** [halirutan/IntelliJ-Key-Promoter-X#105]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is or what could be improved

Currently when I execute an action (i.e. navigate back) which has both a keyboard and mouse shortcut, the extension complains when I use a mouse shortcut.

**Describe the solution you'd like**

The keyboard and mouse shortcuts should be treated identically. I think it would also be interesting to mention any potential mouse shortcuts in the notification.

**Describe alternatives you've considered**

**Additional context**

**Comment by halirutan** [comment]
No, that is not the intention of the plugin. The plugin helps users to eliminate mouse usage by showing keyboard shortcuts that can be used instead. Nothing more.

Please see this instead:

https://plugins.jetbrains.com/plugin/7345-presentation-assistant
