### ISSUE TITLE
PhpStorm 2023.2 EAP doesn't work

### ISSUE THREAD

**Issue by CrazyBoy49z** [halirutan/IntelliJ-Key-Promoter-X#107]
PhpStorm 2023.2 EAP doesn't work

**Comment by Elshid** [comment]
It does not work in any JetBrains Products above build 231.x, which includes 2023.2 EAP.

**Comment by trungklam** [comment]
I made a PR to extend the support for 2023.2 : https://github.com/halirutan/IntelliJ-Key-Promoter-X/pull/109
You can checkout and build the jar file from my branch, then install the it into your IDEs
The build require Java 17, then just need to execute `gradlew build` and the jar file can be found in `IntelliJ-Key-Promoter-X\build\libs`

**Comment by howel52** [comment]
nice work @trungklam   thanks :)

**Comment by halirutan** [comment]
Thanks @trungklam for helping out! The new update will be published soon.

Related: #109
