### ISSUE TITLE
How to unsuppress the suppressed alert for a keyboard shortcut

### ISSUE THREAD

**Issue by Pavitrag** [halirutan/IntelliJ-Key-Promoter-X#108]
**Describe the bug**
This is not a bug request but a "How-to" for the following:
I have suppressed an alert for a key board shortcut which I want to un suppress. However, I am not finding a way to do so in Intellij IDEA community edition. 

**To Reproduce**
Steps to reproduce the behaviour:
Select Suppress alert... option from the notification balloon

**Expected behaviour**
How to unsuppress or re enable alert for the keyboard shortcut

**Screenshots**
NA

**Please also provide:**
 - OS: [e.g. Mac OS X, Linux, Windows] Windows
 - IntelliJ Product [e.g. PyCharm 2019.1.3] IntelliJ IDEA 2023.1.3 (Community Edition)

**Comment by bstring23** [comment]
No IoT devices?

**Comment by halirutan** [comment]
Let me cite the README for your convenience 😄 

> There might be some mouse actions that you don't want to replace by its shortcut. For those, you can press Don't show again in the notification and all suppressed shortcuts will appear in the list below the statistics. **You can re-activate a suppressed item by double-clicking on it in the suppressed list.**
