### ISSUE TITLE
IntelliJ 2023.2 Support 

### ISSUE THREAD

**Issue by Jacob-P-Busby** [halirutan/IntelliJ-Key-Promoter-X#110]
**Is your feature request related to a problem? Please describe.**
2023.2 recently got released and the plugin from the Jetbrains plugin marketplace doesn't support it

**Describe the solution you'd like**
Just an update to the source code adding support for 232.*

**Describe alternatives you've considered**
There is already a pull request [here](https://github.com/halirutan/IntelliJ-Key-Promoter-X/pull/109), however it has a pending workflow

**Comment by andrei-io** [comment]
Any update on this?

**Comment by halirutan** [comment]
And here I am, thinking everyone is enjoying the summer or is on vacation...

I took the #109 of @trungklam and fixed some final things. I'll publish the new release as soon as the CI ran through.
