### ISSUE TITLE
Can you support IntelliJ IDEA 2023.3 EAP version?

### ISSUE THREAD

**Issue by wxywizard** [halirutan/IntelliJ-Key-Promoter-X#113]
![CleanShot 2023-09-28 at 23 27 57@2x](https://github.com/halirutan/IntelliJ-Key-Promoter-X/assets/28422371/15821402-7db8-4952-a161-bed76e365e42)
> Can you support IntelliJ IDEA 2023.3 EAP version?

**Comment by marceloa-asg** [comment]
Is is the same thing for PyCharm 2023.3 EAP

**Comment by halirutan** [comment]
Fixed
