### ISSUE TITLE
No Settings

### ISSUE THREAD

**Issue by apahne** [halirutan/IntelliJ-Key-Promoter-X#12]
I am using v. 1.0.11 on Mac OS. There is no settings panel in the IntelliJ IDEA settings.

**Comment by halirutan** [comment]
**Key Promoter X** is currently in version 5.11. In Mac OS you find the settings here

<img width="799" alt="screen shot 2017-12-01 at 14 44 18" src="https://user-images.githubusercontent.com/511683/33485502-d8aa9abc-d6a6-11e7-8db1-bab0592f46f4.png">
