### ISSUE TITLE
support for pycharm 2024.1

### ISSUE THREAD

**Issue by HjtDevs** [halirutan/IntelliJ-Key-Promoter-X#120]
support for pycharm 2024.1
support for pycharm 2024.1
support for pycharm 2024.1
support for pycharm 2024.1
support for pycharm 2024.1
support for pycharm 2024.1

**Comment by halirutan** [comment]
See here https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/118#issuecomment-2041274963

**Comment by halirutan** [comment]
Duplicate of #118
