### ISSUE TITLE
not working in PhpStorm 2024.2 EAP

### ISSUE THREAD

**Issue by milan-sahana** [halirutan/IntelliJ-Key-Promoter-X#126]
**Update require for PhpStorm 2024.2 EAP**
Currently not working in PhpStorm 2024.2 EAP, please update and create a build so that we can use this plugin in our PhpStorm 2024.2 EAP build.
![Screenshot 2024-06-13 164936](https://github.com/halirutan/IntelliJ-Key-Promoter-X/assets/14888119/ad25d9e9-5e7c-4bce-9919-6ecca4509345)

**Comment by halirutan** [comment]
See https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/128#issuecomment-2428070806
