### ISSUE TITLE
Enable this plugin for Intellij IDEA EAPs

### ISSUE THREAD

**Issue by xstefank** [halirutan/IntelliJ-Key-Promoter-X#128]
**Is your feature request related to a problem? Please describe.**
I would like to use this plugin, and I also want to help test early access builds of IntelliJ products (IDEA in my case).

**Describe the solution you'd like**
Enable this plugin to be installable in EAP versions of IntelliJ IDEA.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

![2024-07-10-1720618454_1554x320](https://github.com/halirutan/IntelliJ-Key-Promoter-X/assets/9353101/cc1ca6ba-a9f0-4ee0-bf11-176e9daface5)

**Comment by halirutan** [comment]
This should be fixed from now on, as I left the "until build" property open. So it should work out of the box for all upcoming versions unless something in the IntelliJ Platform API changes so drastically that it breaks the plugin.
