### ISSUE TITLE
Option to disable buttons in GUI (Savage Mode?)

### ISSUE THREAD

**Issue by will-emmerson** [halirutan/IntelliJ-Key-Promoter-X#15]
I keep using the mouse by accident - would it be possible to have a setting to disable all GUI buttons/actions which have a keyboard shortcut?

**Comment by halirutan** [comment]
Sorry for the very late response. I must have missed this issue. Key Promoter cannot do this and I believe it would not be wise to do this. There are buttons that AFAIK cannot be used by a short-cut. For instance, I always struggle to navigate and control tool-windows completely with the keyboard. I have not researched this in every detail, but I'm almost certain at some point you need the mouse and it would be a disaster to disable all mouse actions.
