### ISSUE TITLE
Suggestion for mouse wheel click (Paste from X clipboard)

### ISSUE THREAD

**Issue by Alexander-Lysenko** [halirutan/IntelliJ-Key-Promoter-X#18]
I use one of JetBrains IDEs on Ubuntu desktop 16.04.4 with GNOME Shell 3.18.5.
GNOME has a special clipboard for a last highlighted text. To paste it, you need to click mouse wheel (or Mouse Button 2). 
Key Promoter is triggered by pressing mouse wheel button and suggests to press it for this command.

![photo_2018-04-23_16-58-54](https://user-images.githubusercontent.com/16338936/39131268-b9b04396-4717-11e8-8761-b6bd68543c1d.jpg)

**Comment by halirutan** [comment]
Unfortunately, I don't create the short-cut strings myself. They come from the IDEA API and to exclude such things as you described, I would need to parse the shortcut string to identify if there was a *real* key suggestion in it or not. I won't fix this at the moment but maybe in future, when I have more time at hand.

Please see also this issue for some more details: https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/10
