### ISSUE TITLE
Suggests to create a shortcut for an action that already has a shortcut

### ISSUE THREAD

**Issue by nbardiuk** [halirutan/IntelliJ-Key-Promoter-X#2]
The plugin keeps suggesting to create a shortcut to the action that already has a shortcut.

It should remind to use existing shortcut instead of suggesting to create a new one.

**Comment by halirutan** [comment]
Can you be more specific? Which version of IDEA and the Key-Promoter-X are you using. What exactly do you click when this happens?

**Comment by nbardiuk** [comment]
Versions:
* Key Promoter X: 5.7.3
* IntelliJ IDEA: 2017.2.2 Build #IU-172.3757.29
* JRE: 1.8.0_152-release-915-b10 amd64
* DE: GNOME 3.24

Keymap is "Default for XWin copy" and contains custom hotkeys :
 * Terminal  _Alt+F12_
 * Maven Projects _Alt+M_

When I use mouse to open Terminal or Maven Projects new popup appears with a message
> Key Promoter
> Want to create a shortcut for Terminal?

**Comment by halirutan** [comment]
Yes, you are correct and I can verify the behaviour. I need to access the active `KeyMapManager` to get the action ID's that you additionally assigned. I'm not doing this right now. Let me see if I can include this in a working manner. Would you be up for testing a pre-version?

**Comment by halirutan** [comment]
If you are feeling lucky, please try the following release candidate. Please pay attention if it breaks something. Now, I see the custom shortcuts, they are inserted in the statistic, etc..

https://github.com/halirutan/IntelliJ-Key-Promoter-X/releases/download/v5.8rc6/Key-Promoter-X-5.8rc6.zip

**Comment by nbardiuk** [comment]
Thanks for such quick fix. I've tested your build on my machine. The issue is fixed and I haven't found any bugs.
