### ISSUE TITLE
Minimum count before notification

### ISSUE THREAD

**Issue by itsaphel** [halirutan/IntelliJ-Key-Promoter-X#20]
Can you add an option for how many times a certain button is used before you show a notification?

You fetch the stats around the same point so it shouldn't be too difficult to add. The amount of 1 click notifications is annoying.

**Comment by halirutan** [comment]
Sounds like a plan. I consider adding this.

**Comment by halirutan** [comment]
Implemented in dev-version and soon to be published. In Settings -> Tools -> Key Promoter X you will find now an additional setting that lets you adjust that only every n-th click on a button will be shown as a notification by the KPX.
