### ISSUE TITLE
Idea: Have Key promoter tailor what is shown in the tips

### ISSUE THREAD

**Issue by dalewking** [halirutan/IntelliJ-Key-Promoter-X#21]
Don't know if it is possible, but thought it would be nice if Key Promoter could control which tips are shown on startup. Had a tip today that was a key combination that I use all the time. Thought it would be nice if the list of tips could be filtered to make tips for keys that I already know and use not show up or lower priority.

**Comment by halirutan** [comment]
Make a decision on startup will be difficult. I have no information about shortcuts. I'm only *reacting* to actions. So if you use an action (buttons, menus, keys, etc), my action-listener is notified. Only *then*, I'm reacting by using IntelliJ's API to find out if the action had a short-cut and if you indeed invoked the action with the mouse, although there is a key-combination available.

However, once you pressed an action that you know the key, you can tell KPX to not show it again

<img width="370" alt="screen shot 2018-07-05 at 15 55 55" src="https://user-images.githubusercontent.com/511683/42327741-c325e0dc-806c-11e8-9fde-6006a41efae4.png">

It then goes into the *ignored list* that you can see in the KPX tool-window.
