### ISSUE TITLE
Positive reinforcement when starting to use shortcut

### ISSUE THREAD

**Issue by rrva** [halirutan/IntelliJ-Key-Promoter-X#22]
The first two or three keyboard shortcuts that are used after a high count of non-usage should generate some kind of positive reinforcement as well. Right now the plugin only gives corrective feedback.

**Comment by halirutan** [comment]
Sorry, I don't work with positive reinforcement. I want you to hate the annoying shortcut messages so much, that for the sake of your sanity, you try to use the keys and not the mouse.

Or to state it differently: The Key Promoter is a small side-project right in the middle of many other projects that I care about. If you think you really need positive reinforcement, clone the repo and work on it. A pull request is always welcome. Please understand, that my time is limited and I have many other things to look after.
