### ISSUE TITLE
Back and forward are not recognized when bound on mouse buttons

### ISSUE THREAD

**Issue by christopheml** [halirutan/IntelliJ-Key-Promoter-X#24]
Platform : Windows 7 Enterprise SP1
IntelliJ version : 2018.2.1
JDK version : 1.8.0_162-b12 amd64

Plugin version : 5.12

**Description**

The `Back` and `Forward` commands are currently bound to `Button4 Click` and `Button5 Click` respectively.

When I click the back button of my mouse, the Key Promoter notification about the `Back` command pops as if I didn't use a proper binding ([see screenshot](https://i.imgur.com/O39wP8E.png)).

**Expected behavior**

No notification from Key Promoter since the `Back` command shortcut is properly bound on a mouse button.

**Comment by halirutan** [comment]
Please see https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/10
