### ISSUE TITLE
Include actions on gutter icons

### ISSUE THREAD

**Issue by nicolaiparlog** [halirutan/IntelliJ-Key-Promoter-X#25]
Mouse actions on gutter icons seem to be ignored, e.g. when I run a test like this ...

![mouse-action](https://user-images.githubusercontent.com/6537432/44839533-555ee680-ac3f-11e8-8ecb-5bc6f71f2bf7.png)

... I get no message (and the stats don't show it either) even though there's a shortcut.

(By the way, :+1: for the great work! :smiley:)

**Comment by halirutan** [comment]
Yep, the Gutter icons are pretty immune to inspections. For the toggling of break-points, I can extract actions and display them. For the other things not even IDEAS `ActionManager` registers them. Sorry

**Comment by nicolaiparlog** [comment]
Too bad, but nothing to be done about.

**Comment by bric3** [comment]
Just in case I opened new ticket on their side hoping for a change in their code base.
