### ISSUE TITLE
restart the idea and catch the error

### ISSUE THREAD

**Issue by MacMargo** [halirutan/IntelliJ-Key-Promoter-X#29]
Plugin 'Key Promoter X' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.AssertionError
    at com.intellij.util.xmlb.MapBinding.deserializeKeyOrValue(MapBinding.java:233)

**Comment by halirutan** [comment]
@MacMargo It seems your statistics file of KeyPromoter got corrupted. Can you try to delete the statistics file like I described here

https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/5#issuecomment-321979777

**Comment by MacMargo** [comment]
wow, it goes well, thanks!
