### ISSUE TITLE
Compatibility: Not compatible with PHPStorm 2019.2 EAP

### ISSUE THREAD

**Issue by rbairwell** [halirutan/IntelliJ-Key-Promoter-X#35]
Whilst running the following:

```
PhpStorm 2019.2 EAP
Build #PS-192.4205.18, built on May 22, 2019
PhpStorm EAP User
Expiration date: June 21, 2019
Runtime version: 11.0.3+12-b262.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=1000, tabs.alphabetical=true
Non-Bundled Plugins: String Manipulation, net.seesharpsoft.intellij.plugins.csv, com.kalessil.phpStorm.phpInspectionsUltimate, izhangzhihao.rainbow.brackets, org.psliwa.idea.composer
```

I am not able to install Key Promoter X via the IDE (it does not show up in the list) and downloading IntelliJ-Key-Promoter-X-2019.1.2.zip and then trying the 'Install from disk' option comes up with an incompatible with this version warning.

**Comment by halirutan** [comment]
@rbairwell I fixed this and it should work on all 192.* versions. I also raised the minimum required version to get rid of a deprecated API call. Please check if everything works as usual.

Ah, yes. And please give the repo a star if you haven't already done so :smile:
