### ISSUE TITLE
Missed shortcuts use wrong icon in tool window if original action does not have icon

### ISSUE THREAD

**Issue by GauthierPLM** [halirutan/IntelliJ-Key-Promoter-X#37]
When an action listed in the tool window does not have any icon, it seems a random icon (from the action above or bellow) is picked from other elements present in the list.

In the screen bellow, the "Declaration or Usage" shortcuts has the icon of the "Build Project" action which is the listed item.
I also noticed that clicking on the items causes the icon to change.

I think a default icon should be provided (or no icon) to avoid this issue.

<img width="541" alt="Capture d’écran 2019-07-05 à 12 21 45" src="https://user-images.githubusercontent.com/2579741/60696249-d9e55a00-9f1f-11e9-9732-462a1dc5140b.png">

**Comment by halirutan** [comment]
@GauthierPLM You are absolutely right. I was brave enough to check that the icon is not null, but I didn't assign an icon when there was no icon. I fixed this and use now the Key Promoter X icon for actions that don't have one themselves.
