### ISSUE TITLE
Disable override when in Presentation Mode

### ISSUE THREAD

**Issue by h1nk** [halirutan/IntelliJ-Key-Promoter-X#39]
It would probably be nice to have a disable/toggle for when in Presentation Mode (probably off by default) as to not be distracting to others.

**Comment by halirutan** [comment]
Actually, this is a great idea. Let me look into this.

**Comment by h1nk** [comment]
I just wanted to make a small clarification of my poor wording: by off by default I meant notifications should be disabled for Presentation Mode by default.

**Comment by halirutan** [comment]
Alright, now we have two more settings that allow you to turn off the KPX in Presentation and Distraction-Free Mode:

![img](http://i.imgur.com/z05pXGC.png)

This will be part of the next **2019.2.2 release**.
