### ISSUE TITLE
Merge conflict using "Settings repository"

### ISSUE THREAD

**Issue by MichaelDemeyer** [halirutan/IntelliJ-Key-Promoter-X#40]
The plugin seem to store in his configuration files the number of time a command was clicked.

This lead to many merge conflicts when using IDEA's "Settings repository" to keep configuration in sync on multiple workstations.

It would be nice to be able to store number of clicks out of configuration files (local only) or to completely disable click tracking.

Thx !

**Comment by halirutan** [comment]
I believe I can fix this without breaking anything else and restrict the storage of the KPX values to local. Let me clear this up and I come back to you.

**Comment by halirutan** [comment]
The roaming for this [was disabled a while ago](https://github.com/halirutan/IntelliJ-Key-Promoter-X/blob/bf3083b44646214f9e66b10b89c8ad152e757e11/src/de/halirutan/keypromoterx/statistic/KeyPromoterStatistics.java#L52) and this should be not an issue anymore.
