### ISSUE TITLE
Suppress all notifications

### ISSUE THREAD

**Issue by kalbert312** [halirutan/IntelliJ-Key-Promoter-X#41]
First, thanks for the great plugin.

Is the recommended way to suppress all notifications from Key Promoter X to use JetBrain's built-in notification settings? I'd prefer to not have any notifications and just periodically check the tool window for suggestions.

Thanks.

**Comment by halirutan** [comment]
Yes, this is right. If you use **Settings | Appearance | Notifications** you can turn off the KPX's ballons but still register your missed shortcuts in the statistics. When you click on "don't show again" in the KPX balloon, then the shortcut will not be shown **and** not registered for the statistics any more.
