### ISSUE TITLE
Add ability to pause tips for 24 hours

### ISSUE THREAD

**Issue by armarti** [halirutan/IntelliJ-Key-Promoter-X#42]
**Is your feature request related to a problem? Please describe.**
This extension is great and I'm sure it'll enhance my productivity. In the long run.

That being said, today and yesterday have been stressful dev days for me and I've found myself clicking "Don't show this shortcut again" more times than I should, for shortcuts I really should learn, but just not _right now_. Now, when I get to a more normal pace, I'll need to remember to go to the extension and re-enable the tips that I disabled. Which is easy enough but I'll definitely forget.

**Describe the solution you'd like**
Three options, all good to me:
1. Add an option to the settings menu to pause the extension for some number of hours, default 24.

2. Notice that, for the last N notifications, I've clicked the "x" (close) button only M milliseconds after it popping up.

   M here is some number of milliseconds that indicate that I'm closing the notification very soon after it appears, indicating that I'm probably not reading it and just closing it, implying that I probably don't want to be shown notifications right now.

   I think for a start you could just guess good values for M and N since guessing wrong wouldn't be a huge deal.

3. If you're a whiz with some time on your hands then maybe the extension can learn my reaction in general to notifications in the IDE and detect if I'm closing your extension's notifiactions faster than normal.

**Describe alternatives you've considered**
Meh, I could disable the extension, then re-enable when I'm feeling it, but again I'll probably forget.

**Additional context**
That's all. Thanks for the extension!

**Comment by halirutan** [comment]
Pausing the notifications automatically, without asking the user will annoy other people when out of the blue the KPX stops. "Asking" them if they like to pause is another additional (and annoying) interruption. Therefore, I've opted for the most simple solution: I added a small checkbox in the Key Promoter X tool-window that lets you snooze notifications as long as it is enabled *or* until you restart IDEA:

![img](http://i.imgur.com/m9MPzLu.png)

Is the arrangement in the tool-window and the wording acceptible?

**Comment by armarti** [comment]
Yes sure that's a fine balance. I still like the idea of it automatically re-enabling itself but this solution is better than needing to a enable/disable in the settings and restart the IDE.

**Comment by koppor** [comment]
Would it be possible to have the "snooze" button right at the prompt? I would like to have a certain prompt being snoozed.

![grafik](https://user-images.githubusercontent.com/1366654/102011532-150ad000-3d45-11eb-95d0-4bb12bfb6a33.png)

Wish:

![grafik](https://user-images.githubusercontent.com/1366654/102011563-3ff52400-3d45-11eb-8dde-07e1269dbc2b.png)
