### ISSUE TITLE
Does not count rename (Shift+F6) when triggered in Java editor

### ISSUE THREAD

**Issue by CodingSpiderFox** [halirutan/IntelliJ-Key-Promoter-X#43]
**To Reproduce**
Steps to reproduce the behaviour:
1. Create new Java class "Test"
2. Open the class in IntelliJ code editor
3. Right click the class name after `public class`
4. Go to menu item Refactor -> Rename
5. Rename to "asd"
6. KeyPromoterX missed shortcut list stays empty
7. In Project structure view, right click" abc" Java file
8. Go to menu Refactor -> Rename
9. Rename to "Test
10. KeyPromoterX missed shortcut list has following contents: 
![image](https://user-images.githubusercontent.com/25173078/64133465-7e780100-cdd6-11e9-8db9-af2c8b67faae.png)

**Expected behaviour**
"Missed count for Shift+F6 should be 2.

**Please also provide:**
ElementaryOS Juno
IntelliJ IDEA 2019.2.1 (Community Edition)
Build #IC-192.6262.58, built on August 20, 2019
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-25-generic
Registry: 
Non-Bundled Plugins: Key Promoter X

**Comment by halirutan** [comment]
Thanks for this report. This is actually a regression that was introduced when I tried to hack [around a bug in IntelliJ](https://youtrack.jetbrains.com/issue/IDEA-219133). To give a TL;DR, certain buttons in IntelliJ fire the action event that something was clicked twice. Fortunately, to each event there is a timestamp which is the same for the duplicate action which is fired. So I hacked around it by comparing these timestamps:

```java
      if (lastEventTime == input.getWhen()) {
        lastEventTime = input.getWhen();
        return;
      }
      lastEventTime = input.getWhen();
```

What slipped through the net was that exactly the action you mention, i.e. renaming through the file editor popup, has always a timestamp of `0`. This leads to that the KPX falsy thinks that it is the same action when the `lastEventTime` *was* zero and you press rename.

You can quickly verify this by pressing the `Settings` button in the toolbar which sets the timestamp correctly and then you try the editor-rename again. It will pop up.

I will hack around that hack by also testing `input.getWhen() != 0` and then hopefully, we can get rid of this.
