### ISSUE TITLE
Don't include title of what is being run for Run shortcut

### ISSUE THREAD

**Issue by rcollette** [halirutan/IntelliJ-Key-Promoter-X#44]
**Is your feature request related to a problem? Please describe.**
Too many repetetive shortcuts listed in Promotor View window.

**Describe the solution you'd like**
At least for the Run command, do not include the name of what was being run (or the option to not include the name)

![image](https://user-images.githubusercontent.com/136476/66206365-e6dc2b80-e67d-11e9-8a72-e209d3dda804.png)

**Comment by halirutan** [comment]
Thanks for creating an issue. I'm aware of this deficiency and I will have a look at it on the weekend. Let's see how much pain it is to unify all these into one `Run` action.
