### ISSUE TITLE
Incompatible with IntelliJ IDEA 2019.3 EAP

### ISSUE THREAD

**Issue by SaarYogev** [halirutan/IntelliJ-Key-Promoter-X#45]
Having the plugin already installed, I updated to EAP version 2019.3
then opening the IDE produced error:
>Plugin Error: Plugin "Key Promoter X" is incompatible (target build range is 191 to 192.*).
The 2019.3 EAP is at build 193.4099

Full Build Details:

- IntelliJ IDEA 2019.3 EAP (Ultimate Edition)
- Build #IU-193.4099.13, built on October 2, 2019
- IntelliJ IDEA EAP User
- Expiration date: November 1, 2019
- Runtime version: 11.0.4+10-b485.1 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Windows 10 10.0
- GC: ParNew, ConcurrentMarkSweep
- Memory: 1498M
- Cores: 4
- Registry: 
- Non-Bundled Plugins: CheckStyle-IDEA, FindBugs-IDEA, com.intellij.ideolog, in.1ton.idea.spring.assistant.plugin, some.awesome

**Comment by RainingNight** [comment]
+1

**Comment by halirutan** [comment]
Thanks for reporting. I will take care of this and I hope to find time at the weekend.

**Comment by electronicboy** [comment]
FWIW, recompiling from the repo provides a plugin which appears to be working fine

**Comment by halirutan** [comment]
New version for 2019.3 EAP is live now.
