### ISSUE TITLE
Wrong shortcut suggestion for re-run on Mac

### ISSUE THREAD

**Issue by GitAnt** [halirutan/IntelliJ-Key-Promoter-X#46]
The shortcut suggestion for the re-run action on a Mac is "command + R" but the actual shortcut is "control + R"

**Comment by halirutan** [comment]
Can you specify which IntelliJ IDE you are using? We fixed an issue not long ago that would exclude the name of the run-configuration in the KPX notification. But I don't think that has something to do with it. I can try it out next week when I'm back on my Mac.

**Comment by GitAnt** [comment]
@halirutan I was working with some scala files but since then I've upgraded intellij and the plugin and now the shortcut is reported correctly (control + shift + R), my current intellij version is 2019.3.1

**Comment by halirutan** [comment]
I love bugs that resolve themselves! :)
