### ISSUE TITLE
Incompatible with IntelliJ IDEA 2020.1 EAP

### ISSUE THREAD

**Issue by goerge** [halirutan/IntelliJ-Key-Promoter-X#47]
Having Key-Promoter-X 2019.3.1 installed, I just updated to the new IDEA 2020.1 EAP which leads to the following startup error:

> Plugin Error: The Key Promoter X (id=Key Promoter X, path=~/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.3803.71/IntelliJ IDEA 2020.1 EAP.app.plugins/Key-Promoter-X, version=2019.3.1) plugin is incompatible (target build range is 191 to 193.*).

IntelliJ Version Details:

> IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.3803.71, built on January 24, 2020
IntelliJ IDEA EAP User
Expiration date: February 23, 2020
Runtime version: 11.0.5+9-b674.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.editor.tabs.open.at.the.end=true, terminal.buffer.max.lines.count=10000, documentation.show.toolbar=true, analyze.exceptions.on.the.fly=true
Non-Bundled Plugins: LimitedWIP, String Manipulation, Lombook Plugin, com.dubreuia, org.asciidoctor.intellij.asciidoc, org.jetbrains.plugins.hocon, org.sonarlint.idea, com.atlassian.bitbucket.references, io.protostuff.protostuff-jetbrains-plugin, net.ashald.envfile, net.seesharpsoft.intellij.plugins.csv, org.intellij.scala, Karma, izhangzhihao.rainbow.brackets

Is there any known incompatibility or just a conservative target build range?

Thanks a lot for your work on this great plugin!

**Comment by halirutan** [comment]
@goerge Just conservative build range since it's bitten me in the past on a different plugin. I'll update it next week and check if everything still works.

**Comment by halirutan** [comment]
Fixed in the release just published

**Comment by yshinkarev** [comment]
Hello.
Again incompatible with IntelliJ IDEA 2020.2 EAP (IU-202.4357.23)
