### ISSUE TITLE
Add hard time option

### ISSUE THREAD

**Issue by johanvergeer** [halirutan/IntelliJ-Key-Promoter-X#50]
**Is your feature request related to a problem? Please describe.**
Right now the popup shows in the bottom right corner of my IDE, which is nice, but it doesn't really force me to use keyboard shortcuts.

I got the idea from [VIM Hardtime](https://github.com/takac/vim-hardtime)

**Describe the solution you'd like**

- Add an option to Key Promotor X Preferences with the text "Give me a hard time", which will open a popup that has to be clicked on instead of the box in the bottom right corner.
- Add a checkbox to the popup to ignore the keyboard shortcut. (For example when it's a button that is rarely used).

I think it is wise to add a checkbox that let's the user disable

**Comment by halirutan** [comment]
I'm not sure when I will have time for this, but it sounds like a fun idea to add!

**Comment by johanvergeer** [comment]
I would like to contribute, but I have the same problem as you. 🕙  😄

**Comment by mirkoalicastro** [comment]
Hi there. This seems a nice feature to have! Are you open to contributions in case? @halirutan

**Comment by mirkoalicastro** [comment]
@halirutan - I just opened a PR. Any feedback is welcome 🙂

**Comment by johanvergeer** [comment]
Hi all,

I wanted to take a look at the hard mode, but I see that it is in the beta branch, and I have no idea what the correct way is to install from that branch, could someone help me out with that?
