### ISSUE TITLE
Some settings aren't preserved after restart

### ISSUE THREAD

**Issue by Insiderser** [halirutan/IntelliJ-Key-Promoter-X#51]
**Describe the bug**
Whenever I change `Clicks before notification is shown` or `Number of invocations before suggest create shortcut` settings, they are reset to default as soon as I restart my IDE. Until restart, those settings are preserved. Other settings (e.g. `Disable in Presentation Mode`) are preserved after restart.

Tested on 3 different IDEs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Key Promoter X settings.
2. Change any numerical field (e.g. `Clicks before notification is shown` or `Number of invocations before suggest create shortcut`).
3. Click OK/Apply to save settings.
4. Restart IDE.

**Expected behaviour**
`Clicks before notification is shown` and `Number of invocations before suggest create shortcut` settings are preserved.

**Actual behaviour**
Those settings are reset to default.

**Please also provide:**
 - OS: Windows
 - Products: Android Studio 3.6.1, IntelliJ IDEA 2019.3.3, CLion 2019.3.4
 - Key Promoter X Version: 2020.1.1

**Comment by halirutan** [comment]
Well, it seems I cannot read documentation :(

Can you please test the release I attached here

https://github.com/halirutan/IntelliJ-Key-Promoter-X/releases/tag/v2020.1.1

by going to **File | Settings | Plugins | gear icon left of "Installed" | Install from disk** and give me feedback if all settings are remembered correctly in Android Studio?

**Comment by Insiderser** [comment]
Works as expected. Thank you!
