### ISSUE TITLE
Make plugin compatible with Pycharm

### ISSUE THREAD

**Issue by phx-srankin** [halirutan/IntelliJ-Key-Promoter-X#54]
**Is your feature request related to a problem? Please describe.**
I installed the plugin into Pycharm but it doesn't seem to render the same popup it does in IntelliJ

**Describe the solution you'd like**
The plugin works with Pycharm

**Describe alternatives you've considered**
I printed the pdf of the keyboard map for Pycharm and taped it to my desk

**Additional context**
![image](https://user-images.githubusercontent.com/45577128/78689736-85567d00-78ab-11ea-9732-f857ad3a6165.png)
![image](https://user-images.githubusercontent.com/45577128/78689827-9b643d80-78ab-11ea-9a68-f1ad9db46159.png)

**Comment by halirutan** [comment]
The plugin works with PyCharm :)

Can you verify that under **File | Settings | Appearance | Notifications** you have set the Key Promoter X notifications to "Balloon"?

**Comment by Barabus** [comment]
Yup, verified.


Regards,Randall Keels
Sent from my iPhone

On Tuesday, April 7, 2020, 8:53 PM, Patrick Scheibe <notifications@github.com> wrote:




The plugin works with PyCharm :)

Can you verify that under File | Settings | Appearance | Notifications you have set the Key Promoter X notifications to "Balloon"?

**Comment by phx-srankin** [comment]
Sorry for the delayed response. For some reason it wasn't working the first time but after restarting or the next day everything looks great!

**Comment by halirutan** [comment]
@phx-srankin Thanks for reporting back! Have fun.
