### ISSUE TITLE
Incompatible with IntelliJ IDEA 2020.2 EAP (IU-202.4357.23)

### ISSUE THREAD

**Issue by yshinkarev** [halirutan/IntelliJ-Key-Promoter-X#56]

**Comment by halirutan** [comment]
I'll push an update on the weekend.

**Comment by goerge** [comment]
@halirutan Sorry to annoy you but did you already push an update? I cannot find anything.

**Comment by halirutan** [comment]
Yep, sometimes life just happens in between and as we all know, no good battle-plan survives the first enemy contact :)
In my case, it was building a new computer and set everything up. I pushed an update a few minutes ago.

**Comment by goerge** [comment]
Works like a charm! Thanks a lot for your great work!
