### ISSUE TITLE
"Want to create a shortcut for null?"

### ISSUE THREAD

**Issue by strawlink** [halirutan/IntelliJ-Key-Promoter-X#6]
![image](https://user-images.githubusercontent.com/6575922/30157396-7baba242-93c2-11e7-8e12-49d1876a7675.png)

Occurs when pressing the cog wheels.

Rider 2017.1.1
Build #RD-171.4456.2813

It doesn't show up after clicking (Don't show again), but I could imagine that there's a better way to fix it :)

**Comment by halirutan** [comment]
Thanks for the report. I fixed the issue and it should not appear again in the next release.
