### ISSUE TITLE
Go to declaration using "ctrl + button1" click triggers notification for "ctrl + B".

### ISSUE THREAD

**Issue by johhor** [halirutan/IntelliJ-Key-Promoter-X#64]
**Describe the bug**
In in a Java project, when using the out of the box shortcut: "ctrl + button 1 click", a balloon notification is triggered for the shortcut "ctrl + b".

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the default notification settings of Key promoter X and IntelliJ
2. In any Java project, initialize a variable and use it in another line.
3. While using the Gnome keymap, press "ctrl + button 1 click" on the variable where it is used to go to the declaration of it.
4. In the bottom right of the screen, a balloon notification will pop up promoting the shortcut "ctrl + b". 

**Expected behaviour**
When using a secondary shortcut (i.e. I have two shortcuts for one function), I do not expect the notification to trigger for the primary shortcut, nor the counter to increment. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5869367/89999327-ed203880-dc8e-11ea-9173-de72e41f746a.png)

**Please also provide:**
 - Ubuntu 20.04
 - IntelliJ Community 2020.2 
 - Key Promoter X Plugin Version: Build for 2020.2

**Comment by halirutan** [comment]
Well, question: Can you trigger this without your hand on the mouse? :)

The whole purpose of the KPX is to force your hand off the mouse. So every time you do something with the mouse and KPX knows a way you can do it without the mouse, it will scream at you. It's definitely worth remembering the shortcuts `Ctrl`+`B`, `Ctrl`+`Alt`+`B` (goto implementation), and `Ctrl` + `U` (goto super-method).
