### ISSUE TITLE
Dragging buttons with keyboard shortcuts set will trigger Key Promoter X

### ISSUE THREAD

**Issue by MaDKaTZe** [halirutan/IntelliJ-Key-Promoter-X#65]
**Describe the bug**
When I press and hold left mouse button on button from either side or bottom panel that has a keyboard shortcut set, drag and drop it, Key Promoter X will show up with key promoting notification.

**To Reproduce**
1. Drag and drop a button from the side/bottom sections that keyboard shortcut set.

**Expected behaviour**
Button is placed at it's new position and Key Promoter X doesn't gets triggered.

**Environment Info**
- OS: Linux
- WebStorm 2020.2 Build #WS-202.6397.88
- Key-Promoter-X 2020.2

**Comment by halirutan** [comment]
You are correct. I added a mouse-motion listener and catch these cases to suppress the notifications when you drag the toolwindow button. Once it's confirmed it doesn't break anything on other platforms, I'll close this as fixed.
