### ISSUE TITLE
support CLion 2020.3

### ISSUE THREAD

**Issue by igordovgaluk** [halirutan/IntelliJ-Key-Promoter-X#68]
the plugin is not compatible with CLion 2020.3 EAP

**Comment by halirutan** [comment]
Yep, I hear you. We have some small features in the pipeline [[1](https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/61), [2](https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/53)] that are already implemented, and I hope I can publish a new version in the upcoming days.
