### ISSUE TITLE
First item in statistics list changes

### ISSUE THREAD

**Issue by halirutan** [halirutan/IntelliJ-Key-Promoter-X#70]
When the first entry in the statistics list happens to be an action that does not have an icon, then it should be presented with the KPX generic icon.
However, what actually happens is that its icon changes depending on mouse clicks into the statistics list. More precisely, it seems to get the icon of the last entry you clicked on.

Strange things seem to be happening somewhere around here, although the approach of checking should be straight forward.

https://github.com/halirutan/IntelliJ-Key-Promoter-X/blob/7689b09f7ce929e1143fe2a45e799dfa8a4f4546/src/de/halirutan/keypromoterx/statistic/StatisticsList.java#L89-L98

**Comment by STANDLEYRICHANDE** [comment]
olá mundo!
