### ISSUE TITLE
Non sticky notifications

### ISSUE THREAD

**Issue by asiby** [halirutan/IntelliJ-Key-Promoter-X#71]
Hello

It would be nice to have the Key-Promoter-X suggestions go away on their own after a few seconds.

Now, they are sticky and end up blocking your view while you are coding; unless to close them manually.

Thank

**Comment by asiby** [comment]
Something was preventing these from auto closing themselves. They are working now.

**Comment by halirutan** [comment]
They shouldn't be sticky and never were supposed to be. One could always view the settings for the Key Promoter X notifications and could change their behaviour, however, right now I can't seem to find them in new IDEA versions. Let me investigate if this changed. We do have a deprecation warning for the Key Promoter notification group that I ignored, and I wonder if this has something to do with it.

**Comment by halirutan** [comment]
> Something was preventing these from auto closing themselves. They are working now.

Still, I should be able to change settings specifically for the KPX notifications and this doesn't seem to work. I'll look into it.

**Comment by asiby** [comment]
This is how you can get the settings in Phpstorm ...

![image](https://user-images.githubusercontent.com/455674/97061401-bd31c300-1564-11eb-90f0-b909297436b4.png)

**Comment by halirutan** [comment]
Yep, it's exactly where I looked and the Key Promoter X setting simply wasn't there... Turns out I didn't have the Key Promoter installed :see_no_evil::see_no_evil:

**Comment by asiby** [comment]
It happens. 🙂
