### ISSUE TITLE
Resize the sections in the Key Promoter X view

### ISSUE THREAD

**Issue by ManuelTS** [halirutan/IntelliJ-Key-Promoter-X#72]
# Problem
I want to resize the sections

- Your missed shortcut list
- Suppress tips for these shortcuts
- Actions

but I cannot find a way to do that. I only want to display the first one "Your missed shortcut list" as you may have guest right, over the time this list grows the most. I want to see more shortcuts I'm missing.

# Solution
- Simple checkboxes to toggle the sections's visibility in settings or key promoter x view
- A click on the section name does the same
- Resize section behavior on the single lines separating the sections. 

# Alternative
Make settings entry for the solution to dis- and enable the single view sections there.

# Other
For the section "Your missed shortcut list" you may provide sorting ASC and DESC:

- Most missed
- Last missed
- Name
- Section / Area

but this is probably another feature request ;)

**Comment by halirutan** [comment]
In the most recent update, I changed the UI of the tool-window a bit. So now the missed and suppressed lists are both scroll-panes and they are wrapped in a split-pane. Therefore, you should be able to resize these two.

As for the "Other" suggestion: If there was only a universe with unlimited free-time :)
