### ISSUE TITLE
Any way for checking used shortcuts statistics?

### ISSUE THREAD

**Issue by azsdaja** [halirutan/IntelliJ-Key-Promoter-X#73]
Hi!
In KeyPromoterX tool window I can see a hitlist of missed shortcuts.
I'm also curious about statistics for shortcuts that I actually used.
Is it possible to obtain such statistics somehow? I don't know where the plugin does store its data and if it's actually readable.

**Comment by halirutan** [comment]
The Key Promoter only tracks actions where you used the mouse aka you "missed" to use the shortcut. Once you missed a shortcut and you have an entry in the Key Promoter tool-window, it will also count when you successfully used the shortcut without the mouse. You can see this in the "nx used" entry:

![image](https://user-images.githubusercontent.com/511683/111116039-baf8f100-8565-11eb-9b4a-ebffbe4f418f.png)

However, are you aware of **Help | Productivity Guide**? It gives you a much better overview of features:

![image](https://user-images.githubusercontent.com/511683/111116171-ebd92600-8565-11eb-9bfb-7492e42e884a.png)
