### ISSUE TITLE
Clearer message for "don't show again"

### ISSUE THREAD

**Issue by Morinator** [halirutan/IntelliJ-Key-Promoter-X#75]
When disabling the notification of the shortcut for some action, it says "don't show again", which for me was kind of misleading because I though it referred to disabling all notifications of the plugin.

Maybe the message should be "don't show again for this shortcut/action" to avoid this ambiguity.

**Comment by halirutan** [comment]
I changed the message to "Disable alert for this shortcut" which should be clearer.

**Comment by grap3fruit** [comment]
@halirutan How to enable alert again? I can't find this.

**Comment by halirutan** [comment]
@halirutan If you have put it on the Suspend List (Disable alert for this shortcut) then just open the Key Promoter tool window and double click on the entry.
