### ISSUE TITLE
Please support IntelliJ IDEA 2021.1 (IU-211.*)

### ISSUE THREAD

**Issue by goerge** [halirutan/IntelliJ-Key-Promoter-X#77]
**Is your feature request related to a problem? Please describe.**
As Key Promoter X requires build `203.*`, it cannot be used in IntelliJ 2021.1 (EAP)
Message from Event Log:
```
Plugin 'Key Promoter X' (version '2020.2.2') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is IU-211.4961.30
```

**Describe the solution you'd like**
Key Promoter X is fully usable in IntelliJ 2021.*

**Describe alternatives you've considered**
No alternatives ;-)

**Additional context**
I'm aware that I'm running an early stage EAP  but I thought it's good to have an issue in place.

**Comment by Mishail** [comment]
![image](https://user-images.githubusercontent.com/278751/110713197-59780180-81b6-11eb-87c0-75eb6b7267b1.png)
Still an issue even with version 2021.1 of the plugin

**Comment by halirutan** [comment]
@Mishail You are right. Stupid mistake. I'll fix it.

**Comment by halirutan** [comment]
The most recent update should now work on all currently available platforms and versions.

Btw, if for some reason the Key Promoter notifications do not show up, please be aware of the following issue that bit me:

https://youtrack.jetbrains.com/issue/IDEA-263928
