### ISSUE TITLE
Add "snooze" notifications for X time option

### ISSUE THREAD

**Issue by RUBenGAMArrarodRiguEZ-ToMtOm** [halirutan/IntelliJ-Key-Promoter-X#78]
**Is your feature request related to a problem? Please describe.**
Sometimes while sharing the screen for presenting or pair programming is good to show how to do the things with the menu for team mates or new joiners for inclusivity or team members with some motor disability. 
It would be good to snooze the notifications for 1 hour or 30 minutes.

Sometimes similar when there are plugins that have conflicting shortcuts with the OS it would be good to not see the popups sometimes the conflicting shortcuts are only for a certain amount of time during the working day, for example when other application is open

(I am aware that this defeats the purpose of the plugin, I am thinking in something faster than having to disable and enable the plugin. At the moment the option that I am using is disabling the plugin.)

When sharing the screen the notification can be distraction and counterproductive to the goal of the screen sharing session.
I am also aware of the Presentation Assistant plugin.

**Describe the solution you'd like**
An option from the tooltip to open a configure window when I can select a snooze option for some amount of time.

**Describe alternatives you've considered**
At the moment the option that I am using is disabling the plugin.

**Additional context**
Thanks for you great work in this plugin, it has helped most of my team to be more productive.

This issue is similar to #50

**Comment by halirutan** [comment]
Are you aware that we already have a checkbox in the Key Promoter X tool-window where you can snooze notifications?

![image](https://user-images.githubusercontent.com/511683/111113796-95b6b380-8562-11eb-895f-a4c5e9ed3956.png)

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
Hi @halirutan for how long are the notifications snoozed by default?

**Comment by halirutan** [comment]
Until you uncheck this box again :)

Also, since I'm not sure you've seen it, there are settings in **Settings | Tools | Key Promoter X** that let you automatically snooze notifications when you're in presentation or distraction-free mode:

![image](https://user-images.githubusercontent.com/511683/112915623-f4516500-90fe-11eb-8778-b5bca52e9fa3.png)

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
Thank you for the detailed explanation, from my side this issue can be closed
