### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by onrblnt** [halirutan/IntelliJ-Key-Promoter-X#79]
I can't open anything after install key promote x to my android studio. I click setting, sdk manager etc, nothing happend. norhing open. only I see ballon notification about missing shortcuts and nothing changes even if I set a shortcut. And I dont know how to remove plugin.

**Comment by halirutan** [comment]
That is weird. Key Promoter has roughly 50000 downloads per month and you are the first to report something like this. Are you sure it's not something else? The Key Promoter really doesn't change things in your IDE. It just listens to mouse clicks you make.

You can remove it by going to **Settings | Plugins** and looking in the **installed** tab. Right click on the plugin should give you a popup menu where you can uninstall the Key Promoter. Best of luck.
