### ISSUE TITLE
"Go to Declaration or Usages" when tab is closed

### ISSUE THREAD

**Issue by elendil-software** [halirutan/IntelliJ-Key-Promoter-X#82]
**Describe the bug**
When a tab is closed either by middle mouse button click or Right-click --> Close, a notification "Go to Declaration or Usages" is displayed

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a few files
2. Click with the middle mouse button or by right-click --> Close to close a tab
3. The notification "Go to Declaration or Usages"

**Expected behaviour**
It should display a notification suggesting to use the shortcut to close the current tab if the action is on the active tab or do nothing if the action is not on active tab.

**Please also provide:**
 - OS: Windows 10 Pro
 - Rider 2021.1.5

**Comment by halirutan** [comment]
Unfortunately, I could not reproduce this with Rider 2021.3.3 (Linux) anymore, but I've seen such things in the past. The problem with these issues is that I can't really do much about them. The Key Promoter relies on _listening_ what the IDE _thinks_ it is doing. So if Rider was sending out a "Go to Declaration" action, there is no way for me to decide if this is correct or not.

However, your issue finally got me testing the plugin with Rider which I usually don't use and it brought up another important issue: The tool windows like "Explorer", "Problems", etc. have changed and I used an ugly hack to show tips for them. After looking into it, I removed the hack completely and relied on something that's also used internally in IntelliJ.

**Comment by julien-tschappat** [comment]
On Windows with version 2021.3.3, the issue seems to be solved when using contextual menu (right click) but remains when using middle click.

**Comment by halirutan** [comment]
Yes, you are right it's still there. We have an open "not my fault" issue. It's unfortunate for the Rider on Windows people, but I can't fix this. Rider sends the information that Go to decl. is used when the tab is closed and I just display it. We have an open issue for this bug that will stay open until Rider fixes the underlying issue

- https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/59
