### ISSUE TITLE
Prompt is forbidden

### ISSUE THREAD

**Issue by liuzhongkai** [halirutan/IntelliJ-Key-Promoter-X#86]
Hello, I clicked on this link and it is unable to prompt. I tried uninstalling, but it didn’t work. What should I do?
<img width="367" alt="WeChatff3d948d22931b6fee88752c6acb9655" src="https://user-images.githubusercontent.com/20887284/140896580-b8e3cb3c-fd6c-4125-b67a-5b89425c13cd.png">

**Comment by halirutan** [comment]
Can you clarify what exactly "it is unable to prompt" means? This link puts the command on the "Suppress tips for these shortcuts" list that you find at the bottom of the Key Promoter X tool window:

![image](https://user-images.githubusercontent.com/511683/152665255-25e5a833-f7f5-4a23-867a-32a71cdd4c83.png)
