### ISSUE TITLE
Compatibility with 2017.3 EAP

### ISSUE THREAD

**Issue by szpak** [halirutan/IntelliJ-Key-Promoter-X#9]
There is on a console:
> WARN: Key Promoter X not loaded: until build 172.SNAPSHOT < IC-173.2290.1

and in fact the plugin (5.9) is not enabled.

**Comment by halirutan** [comment]
Yep, I'm sorry for that. I'm developing on (and for) the latest release and therefore the range of valid versions is capped at `172.*`. I will (without making any claims that it will work) extend the version to include the EAP releases so that you can use it.

**Comment by szpak** [comment]
In fact, I already use a version with patched XML configuration and it works fine. I understand your safeguarding (there were many incompatible changes in Idea API in the past), but on the other hand, maybe it's better to just enable next release by default and wait for the issue reports from the EAP users (than from the "stable" users once GA version is available)?

In README your can even provide information that only the current stable version is officially supported.
