### ISSUE TITLE
False positive alert for "Clone Caret", even though keyboard was used

### ISSUE THREAD

**Issue by sin-azucar** [halirutan/IntelliJ-Key-Promoter-X#92]
**How to reproduce:**
Use the shortcut "Clone caret below" (or "above") as [described in the documentation](https://www.jetbrains.com/help/idea/multicursor.html#add-carets-above-or-below-the-current-caret): Hit Alt (Option) key twice and then hold it, use the arrow keys to insert additional carets below or above.

**Expected behaviour:**
No notification from Key Promoter X is shown, since a keyboard shortcut was used.

**Actual behaviour:**
Key Promoter X shows a notification suggesting to create a shortcut for "Clone Caret below" (or "above") even though the keyboard was used and there is already a shortcut (obviously).
![image](https://user-images.githubusercontent.com/67788972/161009931-e6061b37-e913-4e25-8856-126c48424369.png)

**Comment by halirutan** [comment]
Thanks a lot for your report. This is one of these "special cases". The "Clone Caret Below" (or above) doesn't have a shortcut and the special shortcut with hitting Ctrl twice is handled differently. So when the action happens all that Key Promoter sees is

- You invoked an action several times
- It doesn't have a _real_ shortcut
- You must love to create a shortcut for it :)

I've created a hack around this issue by muting this specific action. It'll be available in the next release.
