### ISSUE TITLE
Allow adding shortcuts to the suppression list via the panel

### ISSUE THREAD

**Issue by allejo** [halirutan/IntelliJ-Key-Promoter-X#96]
**Is your feature request related to a problem? Please describe.**

I've enabled hard mode to learn more shortcuts, but I use specific actions interchangeably because of habits or because my hand is already on my mouse. An example of this is "Go to Declaration," which I use both the kb shortcut and with my mouse.

![image](https://user-images.githubusercontent.com/1246453/182446276-4208a617-2367-4fb5-b712-e29b4e038955.png)

**Describe the solution you'd like**

I'd like to be able to right-click on a shortcut from my missed hitlist and be able to suppress the warning from showing up. I believe there's a "Don't show this again" in non-hard mode notifications but I don't see an option to update this while in hard mode.

**Describe alternatives you've considered**

Disabling hard mode temporarily, trigger the notification bubble, and then reenabling hard mode. But this is tedious for every action I use.

**Additional context**

None

**Comment by halirutan** [comment]
Yes, it seems that's indeed a drawback. I implemented the possibility to double click on the statistics list which moves the item to the suppressed list. The behavior is now symmetric.
